# Generated by Django 5.0.4 on 2024-04-17 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id_favourite',
        ),
        migrations.AddField(
            model_name='match',
            name='id_league',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.league'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='id_league',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='base.league'),
            preserve_default=False,
        ),
    ]
