# Generated by Django 5.0.4 on 2024-04-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_user_id_favourite_match_id_league_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerhistory',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
