# Generated by Django 5.0.4 on 2024-04-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_player_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerhistory',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='playerhistory',
            name='start_date',
            field=models.DateField(),
        ),
    ]
