# Generated by Django 5.0.4 on 2024-04-25 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_playerhistory_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edithistory',
            name='id_user',
        ),
        migrations.RemoveField(
            model_name='match',
            name='id_user',
        ),
        migrations.AddField(
            model_name='edithistory',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        
        migrations.AddField(
            model_name='favourite',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('user', 'id_match')},
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
